name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
    - name: npm test:coverage
      run: |
        npm run test:coverage
    - name: Upload code coverage
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: .build/coverage
      env:
        CI: true
